# Generated by Django 2.2.5 on 2020-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200721_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
