# Generated by Django 2.2.5 on 2020-08-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200727_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='몇명이 머무를건가요?'),
        ),
    ]
